apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 3  # Number of pod replicas
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: saravanan456/node  # Replace with your preferred image version
        ports:
        - containerPort: 3000   # React app default port (or the port you configured)
      imagePullSecrets:
        - name: my-docker-secret  # Replace with your actual secret name

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: LoadBalancer  # Changed from NodePort to LoadBalancer
  selector:
    app: nginx
  ports:
  - protocol: TCP
    port: 80           # Port exposed by the service
    targetPort: 3000    # React app running on container port 3000
